### ISSUE TITLE
Status update failures

### ISSUE THREAD

**Issue by simplytoast1** [NorDroN/homebridge-wideq#25]
When doing device poling in the logs I get the following errors:

TypeError: Cannot use 'in' operator to search for '11' in undefined
    at ModelInfo.enumName (/usr/local/lib/node_modules/wideq/dist/core/model-info.js:69:21)
    at Object.lookupEnum (/usr/local/lib/node_modules/wideq/dist/utils.js:26:25)
    at RefrigeratorStatus.get tempRefrigeratorC [as tempRefrigeratorC] (/usr/local/lib/node_modules/wideq/dist/devices/refrigerator.js:107:29)
    at Reflect.get (<anonymous>)
    at Object.<anonymous> (/usr/local/lib/node_modules/wideq/dist/cli.js:99:66)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/wideq/dist/cli.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

**Comment by pjacobs32** [comment]
Same issue:
TypeError: Cannot use 'in' operator to search for '12' in undefined
    at ModelInfo.enumName (/usr/local/lib/node_modules/wideq/dist/core/model-info.js:69:21)
    at Object.lookupEnum (/usr/local/lib/node_modules/wideq/dist/utils.js:26:25)
    at RefrigeratorStatus.get tempRefrigeratorC [as tempRefrigeratorC] (/usr/local/lib/node_modules/wideq/dist/devices/refrigerator.js:107:29)
    at Object.get (<anonymous>)
    at Object.<anonymous> (/usr/local/lib/node_modules/wideq/dist/cli.js:99:66)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/wideq/dist/cli.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
