### ISSUE TITLE
Error???

### ISSUE THREAD

**Issue by jussin5150** [NorDroN/homebridge-wideq#29]
I'm getting this error in the terminal when I try to get the refresh token. Can anyone help?

hoobs@hoobs:/home/hoobs/.hoobs/etc $ wideq auth -c US -l en-US
(node:24330) UnhandledPromiseRejectionWarning: TokenError: An authentication token was rejected.
    at Function.<anonymous> (/home/hoobs/.hoobs/node_modules/wideq/dist/core/auth.js:89:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/hoobs/.hoobs/node_modules/wideq/dist/core/auth.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:24330) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24330) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jussin5150** [comment]
Any updates here?
