### ISSUE TITLE
Any Idea what that means? UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by archiolochos** [NorDroN/homebridge-wideq#3]
(node:21358) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'options' of null
    at ModelInfo.enumName (/homebridge/node_modules/homebridge-wideq/node_modules/wideq/dist/core/model-info.js:68:40)
    at Object.lookupEnum (/homebridge/node_modules/homebridge-wideq/node_modules/wideq/dist/utils.js:23:25)
    at RefrigeratorStatus.get ecoEnabled [as ecoEnabled] (/homebridge/node_modules/homebridge-wideq/node_modules/wideq/dist/devices/refrigerator.js:149:31)
    at RefrigeratorParser.parserAccessories (/homebridge/node_modules/homebridge-wideq/dist/devices/refrigerator.js:97:28)
    at ParseUtil.parserAccessories (/homebridge/node_modules/homebridge-wideq/dist/lib/ParseUtil.js:36:29)
    at WideQ.<anonymous> (/homebridge/node_modules/homebridge-wideq/dist/index.js:200:68)
    at step (/homebridge/node_modules/homebridge-wideq/dist/index.js:33:23)
    at Object.next (/homebridge/node_modules/homebridge-wideq/dist/index.js:14:53)
    at fulfilled (/homebridge/node_modules/homebridge-wideq/dist/index.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:21358) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)

**Comment by archiolochos** [comment]
seems like 0.1.5 fixed that problem :-)

**Comment by archiolochos** [comment]
in addition to that error:
in HomeKit there is a switch for "EcoEnabled". I am unable to turn it on and the switch is greyed out  (seems uneachable?)
The second switch "IcePlusStatus" works and also turns on/off the function "ExpressFreeze" on my fridge. Temperature for Fridge and for the Freezer works as well as the doorsensor. I Hope that helps.

**Comment by NorDroN** [comment]
Hi!
I think that your refrigerator doesn't have option "EcoEnabled"
Try to update this package, I hope that your problem'll be fixed, but you'll still see switch "EcoEnabled", because it is a hardcode in this package.
You can hide "EcoEnabled" via UI now, but in the future I'll create accessories dynamically.
Temperature for fridge and for freezer are TemperatureSensor now, but I think I can create them like a Thermostat.

**Comment by archiolochos** [comment]
Hi & thanks for you quick answer. you are right: there is no EcoMode built in my fridge. it only has the expressfreeze built in. after the update the error is gone but it seems that the plugin does not work correctly anymore. for example if i try to switch on the expressfreeze mode nothing happens. the temps seem to be correct. 

i added a part from the homebridgelog (debugmode=on)

[3/4/2020, 6:35:33 PM] [WideQ] [INFO] Polling status: 4887b790-c286-11e7-9519-7c1c4e8c52ec: REFRIGERATOR (REFRIGERATOR 2RES1VE61NFWA)
[3/4/2020, 6:35:34 PM] [WideQ] [INFO] Status: 4887b790-c286-11e7-9519-7c1c4e8c52ec: REFRIGERATOR (REFRIGERATOR 2RES1VE61NFWA)
[3/4/2020, 6:35:34 PM] [WideQ] [INFO] - tempRefrigeratorC: 5
[3/4/2020, 6:35:34 PM] [WideQ] [INFO] - tempFreezerC: -20
[3/4/2020, 6:35:34 PM] [WideQ] [INFO] - icePlusStatus: false
[3/4/2020, 6:35:34 PM] [WideQ] [INFO] - freshAirFilterStatus: @RE_STATE_FRESH_AIR_FILTER_MODE_AUTO_W
[3/4/2020, 6:35:34 PM] [WideQ] [INFO] - freshAirFilterStatusText: Automatische
[3/4/2020, 6:35:34 PM] [WideQ] [INFO] - energySavingMode: @RE_SMARTSAVING_MODE_CUSTOM_W
[3/4/2020, 6:35:34 PM] [WideQ] [INFO] - doorOpened: false
[3/4/2020, 6:35:34 PM] [WideQ] [INFO] - tempUnit: ℃
[3/4/2020, 6:35:34 PM] [WideQ] [INFO] - energySavingEnabled: false
[3/4/2020, 6:35:34 PM] [WideQ] [INFO] - locked: false
[3/4/2020, 6:35:34 PM] [WideQ] [INFO] - activeSavingStatus: 0
[3/4/2020, 6:35:34 PM] [WideQ] [INFO] - ecoEnabled: false
[3/4/2020, 6:35:34 PM] [WideQ] [INFO] - waterFilterUsedMonth: 0

**Comment by NorDroN** [comment]
It'd be great if you attach wideq-state.json file with a describe of your device.
Follow [this instruction](https://github.com/ssut/wideq-js) and you'll get this file.
I highly recommend removing your tokens from this file before sending.

**Comment by archiolochos** [comment]
here we go:

{"modelInfo":{},"gateway":{"authBase":"https://at.m.lgaccount.com","apiRoot":"https://eic.lgthinq.com:46030/api","oauthRoot":"https://at.lgeapi.com","country":"AT","language":"de-DE"},"auth":{"accessToken":"","refreshToken":""},"session":"86F0BE057772FBD6AE02980759157F47.nodes_sadap_10","country":"AT","language":"de-DE"}

**Comment by NorDroN** [comment]
You should run `wideq ls` task and then run `wideq monitor ...` task

**Comment by archiolochos** [comment]
sorry for the late repley. here is my output

wideq ls
4887b790-c286-11e7-9519-7c1c4e8c52ec: Kühlschrank (REFRIGERATOR 2RES1VE61NFWA)

wideq monitor:
polling...
no status
polling...
no status
polling...
- tempRefrigeratorC: 5
- tempFreezerC: -20
- icePlusStatus: false
- freshAirFilterStatus: @RE_STATE_FRESH_AIR_FILTER_MODE_AUTO_W
- freshAirFilterStatusText: Automatische
- energySavingMode: @RE_SMARTSAVING_MODE_CUSTOM_W
- doorOpened: false
- tempUnit: ℃
- energySavingEnabled: false
- locked: false
- activeSavingStatus: 0
- ecoEnabled: false
- waterFilterUsedMonth: 0

**Comment by NorDroN** [comment]
If you open `wideq-state.json` now, you'll see a describe of your device. Please, attach this file, it helps me to understand which options your device has.

**Comment by archiolochos** [comment]
[fridge.json.txt](https://github.com/NorDroN/homebridge-wideq/files/4338741/fridge.json.txt)
