### ISSUE TITLE
LG Washer doesn't display

### ISSUE THREAD

**Issue by shaileshck** [NorDroN/homebridge-wideq#30]
Hi,

Have been trying to use Homebridge with your plugin for LG washing machine but get the following error in terminal.

(node:16165) UnhandledPromiseRejectionWarning: TokenError: An authentication token was rejected.
    at Function.<anonymous> (/usr/local/lib/node_modules/homebridge-wideq/node_modules/wideq/lib/core/auth.ts:89:13)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-wideq/node_modules/wideq/dist/core/auth.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16165) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16165) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

and below config done on home bridge

{
            "refresh_token": "0cc7631c1e0a984eeed95d44ff248lab4d27dfbaf2ff8cb33d9db0b9401ec9c0867e7991ce14ad912397552fcefee571",
            "country": "IN",
            "language": "en-US",
            "interval": 10,
            "debug": false,
            "platform": "WideQ"
        }

Pls help to resolve this issue.

Regards

Shailesh K.

**Comment by shaileshck** [comment]
Can you help to address the issue.
