### ISSUE TITLE
LG ACs do not report temperature, operation mode, and don't respond to commands

### ISSUE THREAD

**Issue by vfontes** [NorDroN/homebridge-wideq#6]
I'm trying to add my 2 AC units from LG using this plugin but I'm not having a lot of luck. Several errors appear on the logs, and I'm attaching some screenshots showing what happens on iOS as well.

Interestingly, the errors only occur when the fan setting is on auto. Seems like the API returns a value the plugin is not expecting.

As mentioned in the subject, the ACs do not respond to on/off commands, and it is not possible to set their temperature as well.

Happy to provide any other required information or data.
![IMG_1272](https://user-images.githubusercontent.com/9342763/76919585-1d160c00-68a8-11ea-949e-00eff0fc2dce.PNG)
![IMG_1273](https://user-images.githubusercontent.com/9342763/76919590-2010fc80-68a8-11ea-84b2-49340eb2b68b.PNG)
![IMG_1274](https://user-images.githubusercontent.com/9342763/76919593-20a99300-68a8-11ea-8db1-17b11502a35c.PNG)
![IMG_1275](https://user-images.githubusercontent.com/9342763/76919598-21422980-68a8-11ea-968d-ef31af60b355.PNG)
![IMG_1276](https://user-images.githubusercontent.com/9342763/76919601-22735680-68a8-11ea-9c16-0f4d000b4a0a.PNG)
[config.json.txt](https://github.com/NorDroN/homebridge-wideq/files/4346672/config.json.txt)
[homebridge.log.txt](https://github.com/NorDroN/homebridge-wideq/files/4346673/homebridge.log.txt)

**Comment by NorDroN** [comment]
It'd be great if you attach `wideq-state.json` file with a describe of your device.

**Comment by vfontes** [comment]
Hi! Thanks for getting back to me. :)

Not sure what exactly was meant by a description of the device. I checked LG's website but it seems like manuals and everything else is available in Portuguese only, unfortunately. I translated the webpage to English using Google Translator, you can find it here: https://translate.google.com/translate?sl=auto&tl=en&u=https%3A%2F%2Fwww.lg.com%2Fbr%2Far-condicionado-residencial%2Flg-S4-W12JA31A

In any case, it's a **wall-mounted LG AC unit, model `S4-W12JA31A`, with cooling and heating capabilities.** I'm happy to run any tests if needed, so if you need something even more specific, don't be shy. :)

Another thing probably worth mentioning is that I'm able to monitor and control the AC normally using example.py from https://github.com/sampsyo/wideq. So maybe the wideq implementation used by homebridge-wideq might not be up to date?

This is the `wideq-state.json` file I used to obtain the access token to set up homebridge-wideq with:
```
{
    "auth": {
        "accessToken": "REDACTED",
        "refreshToken": "REDACTED"
    },
    "country": "BR",
    "gateway": {
        "apiRoot": "https://aic.lgthinq.com:46030/api",
        "authBase": "https://br.m.lgaccount.com",
        "country": "BR",
        "language": "pt-BR",
        "oauthRoot": "https://br.lgeapi.com"
    },
    "langPackModel": {},
    "langPackProduct": {},
    "language": "pt-BR",
    "modelInfo": {},
    "session": "REDACTED"
}
```

I'm attaching the file [wideq_state_from_sampsyo_wideq.json.txt](https://github.com/NorDroN/homebridge-wideq/files/4354714/wideq_state_from_sampsyo_wideq.json.txt) which was generated using `example.py` from https://github.com/sampsyo/wideq. It has **a lot** more information on it, so I thought it could be useful.

And finally, here's an example session showing how it is possible to control this AC unit using `example.py` from https://github.com/sampsyo/wideq. During this session, I:
* Monitored a running AC unit.
* Turned off a running AC unit.
* Attempted to set the temperature to 25 Celsius, but got an error.
* Attempted to set the temperature to 77 Fahrenheit (25 C), and it worked.
```
pi@raspberrypi:~/wideq $ ./example.py --help
usage: example.py [-h] [--country COUNTRY] [--language LANGUAGE] [--verbose]
                  [CMD] [ARGS [ARGS ...]]

Interact with the LG SmartThinQ API.

positional arguments:
  CMD                   one of: ls, mon, ac-mon, set-temp, turn, ac-config
  ARGS                  subcommand arguments

optional arguments:
  -h, --help            show this help message and exit
  --country COUNTRY, -c COUNTRY
                        country code for account (default: US)
  --language LANGUAGE, -l LANGUAGE
                        language code for the API (default: en-US)
  --verbose, -v         verbose mode to help debugging
pi@raspberrypi:~/wideq $ ./example.py -v ls
2020-03-19 10:07:55 DEBUG [wideq.example] State file found '/home/pi/wideq/wideq_state.json'
2020-03-19 10:07:55 DEBUG [wideq.example] State file found '/home/pi/wideq/wideq_state.json'
d27c5030-7149-11d3-80b3-7440be56f323: AC Quarto (AC RAC_056905_WW)
d27c2920-7149-11d3-80b2-7440be9260fa: AC Sala (AC RAC_056905_WW)
2020-03-19 10:07:56 DEBUG [wideq.example] Wrote state file '/home/pi/wideq/wideq_state.json'
2020-03-19 10:07:56 DEBUG [wideq.example] Wrote state file '/home/pi/wideq/wideq_state.json'
pi@raspberrypi:~/wideq $ ./example.py -v mon d27c2920-7149-11d3-80b2-7440be9260fa
2020-03-19 10:08:22 DEBUG [wideq.example] State file found '/home/pi/wideq/wideq_state.json'
2020-03-19 10:08:22 DEBUG [wideq.example] State file found '/home/pi/wideq/wideq_state.json'
Polling...
- Operation: @AC_MAIN_OPERATION_RIGHT_ON_W
- OpMode: @AC_MAIN_OPERATION_MODE_COOL_W
- WindStrength: @AC_MAIN_WIND_STRENGTH_NATURE_W
- TempUnit: NS
- TempCur: 27 (0.5-39.5)
- TempCfg: 25 (18-30)
- GroupType: 1
- GroupType: 1 (18-30)
- SleepTime: 0 (30-420)
- OnTime: 0 (0-1440)
- OffTime: 0 (0-1440)
- RacAddFunc: @NON
- ExtraOp: @OFF
- DiagCode: @AC_SMART_DIAGNOSIS_RESULT_NORMAL_S
- AirClean: @AC_MAIN_AIRCLEAN_OFF_W
- AutoDry: @ON
- PowerSave: @OFF
- WDirVStep: @100
- WDirHStep: @OFF
- TempLimitMax: 0
- TempLimitMax: @OFF
- TempLimitMin: 0
- TempLimitMin: @OFF
- DuctZoneType: 0
- DuctZoneType: @OFF
- ZoneControl: 0
- ZoneControl: @OFF
- DRED: 0
- DRED: @OFF
- SensorPM1: 0 (0-1000)
- SensorPM2: 0 (0-1000)
- SensorPM10: 0 (0-1000)
- AirPolution: 0 (0-1000)
- HumidityCfg: 0
- HumidityCfg: 0 (0-1000)
- WaterTempCoolMin: 0
- WaterTempCoolMin: 0 (0-1000)
- WaterTempCoolMax: 0
- WaterTempCoolMax: 0 (0-1000)
- WaterTempHeatMin: 0
- WaterTempHeatMin: 0 (0-1000)
- WaterTempHeatMax: 0
- WaterTempHeatMax: 0 (0-1000)
- HotWaterTempMin: 0
- HotWaterTempMin: 0 (0-1000)
- HotWaterTempMax: 0
- HotWaterTempMax: 0 (0-1000)
- SensorHumidity: 0 (0-100)
- TotalAirPolution: 0 (0-1000)
- SensorMon: @OFF
- CleanDry: 0
- CleanDry: @OFF
- ProductStatus: 0
- ProductStatus: @OFF
- AirMonitoring: 0
- AirMonitoring: @OFF
- Humidification: 0
- Humidification: @OFF
- AirFast: 0
- AirFast: @OFF
- AirRemoval: 0
- AirRemoval: @OFF
- AirUVDisinfection: 0
- AirUVDisinfection: @OFF
- WatertankLight: 0
- WatertankLight: @OFF
- SignalLighting: @OFF
- WDirUpDown: @OFF
- WDirLeftRight: @OFF
- WSwirl: 0
- WSwirl: @OFF
- Jet: @OFF
- LowHeating: @OFF
- CirculateStrength: 0
- CirculateStrength: @OFF
- CirculateDir: 0
- CirculateDir: @OFF
- AntiBugs: @OFF
- IceValley: @OFF
- Humsave: 0
- Humsave: @OFF
- WaterTempCur: 0
- WaterTempCur: @OFF
- HotWaterTempCur: 0
- HotWaterTempCur: @OFF
- HotWaterTempCfg: 0
- HotWaterTempCfg: @OFF
- HotWaterMode: 0
- HotWaterMode: @OFF
- HotWater: 0
- HotWater: @OFF
- AWHPTempCfgSwitch: 0
- AWHPTempCfgSwitch: @OFF
- AirTempCoolMin: 0
- AirTempCoolMin: @OFF
- AirTempCoolMax: 0
- AirTempCoolMax: @OFF
- AirTempHeatMin: 0
- AirTempHeatMin: @OFF
- AirTempHeatMax: 0
- AirTempHeatMax: @OFF
- WaterInTempCur: 0
- WaterInTempCur: @OFF
- AWHPWATempControlSta: 0
- AWHPWATempControlSta: @OFF
- DisplayControl: @ON
- SmartCare: @OFF
- TwoSetCoolTemp: 0 (0-50)
- TwoSetHeatTemp: 0 (0-50)
- TwoSetCoolUSL: 0 (0-100)
- TwoSetCoolLSL: 0 (0-100)
- TwoSetHeatUSL: 0 (0-100)
- TwoSetHeatLSL: 0 (0-100)
- TwoSetACOState: @NOP
- TwoSetModeDeadband: 0 (0-10)
- TwoSetState: @OFF
^C2020-03-19 10:08:27 DEBUG [wideq.example] Wrote state file '/home/pi/wideq/wideq_state.json'
2020-03-19 10:08:27 DEBUG [wideq.example] Wrote state file '/home/pi/wideq/wideq_state.json'
pi@raspberrypi:~/wideq $ ./example.py -v turn d27c2920-7149-11d3-80b2-7440be9260fa off
2020-03-19 10:09:19 DEBUG [wideq.example] State file found '/home/pi/wideq/wideq_state.json'
2020-03-19 10:09:19 DEBUG [wideq.example] State file found '/home/pi/wideq/wideq_state.json'
2020-03-19 10:09:21 DEBUG [wideq.example] Wrote state file '/home/pi/wideq/wideq_state.json'
2020-03-19 10:09:21 DEBUG [wideq.example] Wrote state file '/home/pi/wideq/wideq_state.json'
pi@raspberrypi:~/wideq $ ./example.py -v turn d27c2920-7149-11d3-80b2-7440be9260fa on
2020-03-19 10:09:37 DEBUG [wideq.example] State file found '/home/pi/wideq/wideq_state.json'
2020-03-19 10:09:37 DEBUG [wideq.example] State file found '/home/pi/wideq/wideq_state.json'
2020-03-19 10:09:48 DEBUG [wideq.example] Wrote state file '/home/pi/wideq/wideq_state.json'
2020-03-19 10:09:48 DEBUG [wideq.example] Wrote state file '/home/pi/wideq/wideq_state.json'
pi@raspberrypi:~/wideq $ ./example.py -v set-temp d27c2920-7149-11d3-80b2-7440be9260fa 25
2020-03-19 10:10:04 DEBUG [wideq.example] State file found '/home/pi/wideq/wideq_state.json'
2020-03-19 10:10:04 DEBUG [wideq.example] State file found '/home/pi/wideq/wideq_state.json'
Traceback (most recent call last):
  File "./example.py", line 269, in <module>
    main()
  File "./example.py", line 265, in main
    example(args.country, args.language, args.verbose, args.cmd, args.args)
  File "./example.py", line 206, in example
    example_command(client, cmd, args)
  File "./example.py", line 175, in example_command
    func(client, *args)
  File "./example.py", line 137, in set_temp
    ac.set_fahrenheit(int(temp))
  File "/home/pi/wideq/wideq/ac.py", line 167, in set_fahrenheit
    self.set_celsius(self.f2c[f])
KeyError: 25
pi@raspberrypi:~/wideq $ ./example.py -v set-temp d27c2920-7149-11d3-80b2-7440be9260fa 77
2020-03-19 10:10:09 DEBUG [wideq.example] State file found '/home/pi/wideq/wideq_state.json'
2020-03-19 10:10:09 DEBUG [wideq.example] State file found '/home/pi/wideq/wideq_state.json'
2020-03-19 10:10:12 DEBUG [wideq.example] Wrote state file '/home/pi/wideq/wideq_state.json'
2020-03-19 10:10:12 DEBUG [wideq.example] Wrote state file '/home/pi/wideq/wideq_state.json'
pi@raspberrypi:~/wideq $
```
[wideq_state_from_sampsyo_wideq.json.txt](https://github.com/NorDroN/homebridge-wideq/files/4354714/wideq_state_from_sampsyo_wideq.json.txt)

**Comment by bayramog** [comment]
Same here. I successfully added my LG AC to homebridge. The plugin gets on-off status and current temperature value successfully. But cannot get status of heat or cool and target temperature. Also I cannot set cool status, on-off status, and target temperature.
