### ISSUE TITLE
(node:3827) UnhandledPromiseRejectionWarning - during running wide

### ISSUE THREAD

**Issue by Tymo3** [NorDroN/homebridge-wideq#8]
Hi,
I have an error during running wideq

1. running as follow
wideq auth -c PL -l pl-PL

2. then copy, paste, login, paste

3. then error
```
(node:3827) UnhandledPromiseRejectionWarning: Error: write EPROTO 3069158416:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../deps/openssl/openssl/ssl/statem/statem_clnt.c:2150:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
(node:3827) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3827) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

any guess?

t

**Comment by atkinsonar** [comment]
Running Raspbian-Homebridge-v1.0.4
Node.js v12.16.2
Npm v6.14.4
homebridge-wideq v0.1.8

Seeing same issue here, with a different location code. running per below steps...
1) wideq auth -c US -l en-US
2) Get prompt to login here, which I do, and paste the returned URL back in as prompted.
3) Error below received.

```
 (node:23023) UnhandledPromiseRejectionWarning: Error: write EPROTO 1995667920:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1942:
 
     at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
 (node:23023) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
 (node:23023) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by atkinsonar** [comment]
Followed some similar tutorials using some other forums, and exposed some further error messages, not sure if this will help hone in on it, seems almost to be an API or protocol change for the token retrieval?
```

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  [Previous line repeated 2 more times]
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='aic.lgthinq.com', port=46030): Max retries exceeded with url: /api/member/login (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1056)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 269, in <module>
    main()
  File "example.py", line 265, in main
    example(args.country, args.language, args.verbose, args.cmd, args.args)
  File "example.py", line 206, in example
    example_command(client, cmd, args)
  File "example.py", line 175, in example_command
    func(client, *args)
  File "example.py", line 33, in ls
    for device in client.devices:
  File "/var/lib/homebridge/custom_components/wideq/wideq/client.py", line 126, in devices
    self._devices = self.session.get_devices()
  File "/var/lib/homebridge/custom_components/wideq/wideq/client.py", line 117, in session
    self._session, self._devices = self.auth.start_session()
  File "/var/lib/homebridge/custom_components/wideq/wideq/core.py", line 362, in start_session
    self.gateway.country, self.gateway.language)
  File "/var/lib/homebridge/custom_components/wideq/wideq/core.py", line 258, in login
    return lgedm_post(url, data)
  File "/var/lib/homebridge/custom_components/wideq/wideq/core.py", line 202, in lgedm_post
    res = session.post(url, json={DATA_ROOT: data}, headers=headers)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='aic.lgthinq.com', port=46030): Max retries exceeded with url: /api/member/login (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1056)')))
```

**Comment by NorDroN** [comment]
I think, you should see #4
